### ISSUE TITLE
[Feature Request] Put /Themes and /Splashes in Anemone3DS Folder on SD Root

### ISSUE THREAD

**Issue by WubTheGame** [astronautlevel2/Anemone3DS#55] opened 2017-09-05 15:33 UTC
Not Too hard right? would be convenient for having them both in one place and not cluttering up your SD Root even more.

                                     | Themes
                         Anemone3DS |
                                     | Splashes

**Comment by astronautlevel2** [comment] 2017-09-05 16:08
Marking this as a duplicate of #31 which plans on adding support for custom paths as part of a full custom config feature

**Closed by astronautlevel2** 2017-09-05 16:08 UTC

**Comment by WubTheGame** [comment] 2017-09-05 16:41
Ok.
