### ISSUE TITLE
Qr code feature broke and won't work properly

### ISSUE THREAD

**Issue by sekushi18** [astronautlevel2/Anemone3DS#225] opened 2020-06-27 20:38 UTC
Hello,

First time using git hub for issues, But anyways never knew to press a and currently no file of the arm 11 error but anyways the program works though qr code bit never stops displaying "Loading QR Scanner..." I can press be which shows it did load but won't do much else. I can however still download off the 3ds from the theme list though.

using new 3dsxl, last stable release currently of luma and anemone.
![IMG_20200627_132504_2](https://user-images.githubusercontent.com/34662660/85931746-829c7000-b87b-11ea-885f-c51ac63df55f.jpg)

**Comment by Shizz00** [comment] 2020-06-28 23:11
I have the same problem, newly hacked 2ds (6 hours ago, with the 3ds.hacks.guide).

**Comment by astronautlevel2** [comment] 2020-07-01 17:41
Duplicate of #189, please try the build listed in that issue.

**Closed by astronautlevel2** 2020-07-01 17:41 UTC
