### ISSUE TITLE
ARM 11 Crash

### ISSUE THREAD

**Issue by 1031982** [astronautlevel2/Anemone3DS#264] opened 2022-03-01 06:18 UTC
**Description**
I have been able to cause a crash forcing me to restart the system.

**Steps to reproduce**
1. Open Anemone3DS
2. Tap the world icon to load up the online listings of themes
3. Highlight any theme listed
4. Press Y to preview the theme
5. After the preview loads, press the home button
6. Close Anemone3DS VIA X button or trying to open another program

**Expected behavior**
The expected behavior is that the program would close, and if need be, the newly selected program would open.

**Screenshots**
![crash](https://user-images.githubusercontent.com/9312520/156115596-06af1d88-d03f-474a-92f7-fc8257fbc0d8.jpg)

**Crash dumps**
I have two crash dumps :
https://drive.google.com/file/d/1_GlyDKxWHJqwiMrsjmcLRoQe-qvnEm_L/view?usp=sharing

https://drive.google.com/file/d/1yEBy5xmtN1nHQViaS83XlElqY9raT4M_/view?usp=sharing

**System information**
*System model* New2DS XL

*System firmware version* 11.15.0-47U (this can be found in the System Settings applet by default)

*Anemone3DS version* v2.2.0

*Luma3DS version* 10.2.1

**Comment by Helloman892** [comment] 2022-03-01 11:25
If ever we needed an excuse to lock out the home button, @astronautlevel2, this is it.

**Comment by astronautlevel2** [comment] 2022-05-22 15:33
I'd rather try to solve the underlying issue causing the crash than simply disable the home button, even though it's not the recommended way of closing the application. It's possible we could lock out the home button during specifically previewing themes, but even that feels a bit sketchy for me. 

It appears the issue is occurring in the audio thread where when quitting the browser doesn't stop the audio thread properly. We'll discuss this further and decide on a solution (whether we just want to disable the home button mainly).

**Comment by Helloman892** [comment] 2022-06-11 09:06
Hi OP, could you test that again with this? This is a build of the latest commit on `master`.![image](https://user-images.githubusercontent.com/1565516/173181391-d492a071-9350-47fa-aced-001db5a2c088.png)

**Comment by 1031982** [comment] 2022-06-13 09:25
Nope, still gets an error. Here is a screen shot and the dump :
![a_error](https://user-images.githubusercontent.com/9312520/173322746-a4be6f54-c025-4f45-9864-d8d96b926c29.jpg)

https://drive.google.com/file/d/1_Y1bH1P5a_NrgiuSrpBPUB0KeiJKTRlP/view?usp=sharing

**Comment by Helloman892** [comment] 2022-06-14 10:14
cc @LiquidFenrir, did i misunderstand what #270 was fixing?

**Comment by Helloman892** [comment] 2024-02-23 18:56
@1031982 Closing this as **fixed**, unless you can still replicate this on the current latest release.

**Closed by Helloman892** 2024-02-23 18:56 UTC
Labels: bug, further research needed
