### ISSUE TITLE
v2.0.0 - Pressing (Start) during theme preview leads to ARM11 crash

### ISSUE THREAD

**Issue by TurdPooCharger** [astronautlevel2/Anemone3DS#158] opened 2018-05-10 17:31 UTC
[crash_dump_00000001.zip](https://github.com/astronautlevel2/Anemone3DS/files/1992585/crash_dump_00000001.zip)

![preview bug](https://user-images.githubusercontent.com/35666439/39883926-35a782c0-5456-11e8-9c25-8f9e88724a25.png)

**Noticed but happens less consistently.** 
- Sometimes it crashes after previewing several themes; no (START) button involved.
- Other times it crashes when (HOME) button is pressed during theme preview.
- More rare, it'll crash when (HOME) or (Start) button is pressed in theme selection menu after previewing several themes.

**Comment by astronautlevel2** [comment] 2018-05-10 19:40
The other ones at the bottom are likely separate issues (minus the HOME button one) and I cannot replicate them.

This build should fix the crashing when you press start (and probably HOME?): 
![QR Code](https://cdn.discordapp.com/attachments/366999300594728960/444222258928680991/Anemone3DS.cia_qr.png)

**Comment by TurdPooCharger** [comment] 2018-05-10 21:00
**v2.0.0-7beb9b72**
Pressing (HOME) button while in theme preview and then resuming back to Anemone causes the 3DS to freeze. The transition back to Anemone takes a while. BGM stops playing and every button is nonresponsive, save for (Power) in turning off the 3DS.

**Comment by astronautlevel2** [comment] 2018-05-10 21:18
This should disable HOME button entirely.

Are the other bugs you mentioned in the OP fixed?

![QR](https://cdn.discordapp.com/attachments/366999300594728960/444246794499522561/Anemone3DS.cia_qr.png)

**Comment by astronautlevel2** [comment] 2018-05-11 01:14
I think this should fix it (at least, I can't replicate it anymore):

![QR Code](https://cdn.discordapp.com/attachments/366999300594728960/444305948916580374/Anemone3DS.cia_qr.png)

**Comment by TurdPooCharger** [comment] 2018-05-11 02:45
That last QR gives a download for **v2.0.0-cb6f90ad**, same serial as the second build.

I tested it anyway in case the build was different despite the same name.

[crash_dump_00000074.zip](https://github.com/astronautlevel2/Anemone3DS/files/1993796/crash_dump_00000074.zip)

I think I found a way to make it crash consistently, which is user abuse. Pressing (Y) super rapidly usually triggers it.

**Comment by astronautlevel2** [comment] 2018-05-11 11:44
It seems like there was a race condition with it starting to queue new music before the old one was done playing - unfortunately, I can't test this theory due to the fact that when I hook up the debugger it slows down the thread enough to prevent the race condition from occurring. I think I fixed it, would you mind testing?

![QR Code](https://cdn.discordapp.com/attachments/366999300594728960/444464689867653130/Anemone3DS.cia_qr.png)

**Comment by TurdPooCharger** [comment] 2018-05-11 13:00
On my [4 GB/32 KB] setup for the 4th QR code download, also assigned as **v2.0.0-cb6f90ad**

- The stuck music track with fast (Y) presses is gone. :+1: 
- These crashes occurred on my 1st and 4th run sessions with the rapid (Y) and (left/right) scrolling when previewing randomly picked themes. 

[crash_dump_00000003.zip](https://github.com/astronautlevel2/Anemone3DS/files/1995331/crash_dump_00000003.zip)

[crash_dump_00000004.zip](https://github.com/astronautlevel2/Anemone3DS/files/1995359/crash_dump_00000004.zip)

**Comment by astronautlevel2** [comment] 2018-05-11 13:15
I can't replicate this at all, it seems to work fine on my console.

**Comment by TurdPooCharger** [comment] 2018-05-11 13:27
I usually get it to appear when you first turn on the 3DS, launch Anemone, go crazy with the preview selection, exit out of Anemone with the (Start) button, launch Anemone again, and preview select randomly.

It doesn't happen as often like the previous builds, and it doesn't seem to happen if its your first live session with Anemone when the 3DS is on.

It doesn't show up when using Anemone like a normal 3DS user with patience.

**Comment by TurdPooCharger** [comment] 2018-05-11 13:43
@astronautlevel2 , I take that back.

I got it to crash by preview selecting themes with one press (Y), let the music play a bit (about 3 secs wait), exit back out with another (Y), and scrolling up/down with normal speed where I'm not trying to beat the icon cache loading first.

How themes are in your collection?

**Comment by astronautlevel2** [comment] 2018-05-11 13:50
I have 11 themes though I don't know how much that's contributing to it.

Mind testing with this? It should clear all stuff properly now: ![Test](https://cdn.discordapp.com/attachments/366999300594728960/444496577676181514/Anemone3DS.cia_qr.png)

**Comment by TurdPooCharger** [comment] 2018-05-11 14:06
**v2.0.0-dcaac032** 
:pensive:
[crash_dump_00000007.zip](https://github.com/astronautlevel2/Anemone3DS/files/1995547/crash_dump_00000007.zip)

Install Anemone > Launch Anemone > preview several themes > exit with (Start) at theme selection menu > launch Anemone again > preview several themes > crash.

**Comment by astronautlevel2** [comment] 2018-05-11 16:15
I can't replicate this, given that most of the bugs reported here have been solved, and the remaining ones cannot be reproduced, I'm going to close this issue for now.

**Closed by astronautlevel2** 2018-05-11 16:15 UTC
Labels: bug, could not reproduce, implemented/solved, wontfix

**Comment by TurdPooCharger** [comment] 2018-05-11 21:47
Back.

@astronautlevel2 , the bug may be based on previewing certain themes triggers the crash.

I found one that always crashes on me. It will install fine in a single or shuffle install.
 
`096 - NES - Balloon Fighter`

![preview](https://user-images.githubusercontent.com/35666439/39948278-39f0ecfc-5543-11e8-8195-905763af4c78.png)

**Comment by astronautlevel2** [comment] 2018-05-11 22:52
Could you send your zip? Thanks.

**Comment by TurdPooCharger** [comment] 2018-05-11 23:25
Having trouble on my end uploading here on GitHub. There's a 10mb file limit. Expect a PM from GBAtemp soon.

**Comment by TurdPooCharger** [comment] 2018-05-13 11:52
I checked those bad themes by removing their .ogg music files to see if that stops the crashes. I also took themes that work with preview and swapped their .ogg with ones from bad ones. It's the definitely the .ogg.

Does your music previewer handles sound files that are mono? All the my working themes have stereo OGG and bad themes with mono. 

* Cross comparison made in mp3tag v2.86.

**Comment by astronautlevel2** [comment] 2018-05-13 13:04
The only themes I can find at all that behave like this are official themes posted on theme piracy subreddits.

We do not support piracy so therefore I am not going to put a huge effort into fixing this. However, I will prevent it from crashing by preventing it from playing the BGM at all if it detects a mono ogg file (see fa37bcec99aafb969f84623a4df0a930d2f044ce).

If legitimate themes from legitimate sources are found to be using mono ogg I may look into it more.

**Comment by TurdPooCharger** [comment] 2018-05-13 14:05
Lmao. v2.0.1 does music preview on speed.

**Comment by astronautlevel2** [comment] 2018-05-13 14:10
I uploaded the wrong CIA/3DSX, it's fixed now.
