### ISSUE TITLE
Closing the system while running the application causes it to freeze

### ISSUE THREAD

**Issue by ghost** [astronautlevel2/Anemone3DS#172] opened 2018-05-27 23:38 UTC
Same as title. No matter what you are doing, if you close the system (i.e. sleep mode), it will freeze and make you hold the power button to turn it off. This is on a N3DS.

**Comment by TurdPooCharger** [comment] 2018-05-31 19:50
I tried putting my N3DSXL to sleep mode with the v2.0.1 / .3dsx.

It does not freeze or hang up when...
- Browsing in Theme Plaza > sleep mode > reopen 3DS
- Previewing a theme from Theme Plaza > sleep mode > reopen 3DS
- Previewing a theme from Theme Plaza > (HOME) button > Resuming Anemone (HBL injected in AR Games)

It will freeze when...
- Browsing in Theme mode > sleep mode > reopen 3DS
- Previewing a theme you have in your collection > sleep mode > reopen 3DS
- Can't use (HOME) button in Theme mode.

The original reason why (HOME) button was disabled is found in issue #158 due to problems with the v2.0.0 theme previewer, which appears to be solved in v2.0.1. You should be good to go in enabling it again. :+1:

**Comment by astronautlevel2** [comment] 2018-05-31 23:52
I'm currently waiting on a PR to libctru (https://github.com/smealum/ctrulib/pull/406) to be either merged or rejected so I know where to proceed with this.

**Comment by TurdPooCharger** [comment] 2018-06-02 08:53
@astronautlevel2, ah drats. I take it back. I forgot about issue #163 freezing when exiting back to HOME Menu. Any theories what could be the cause of the freeze? It seems weird this is a now problem when prior versions of Anemone used to exit out.

**Comment by astronautlevel2** [comment] 2018-06-02 12:48
I have some ideas, but I'd rather hear back from smealum/ctrulib#406 before pursuing anything.

**Comment by Leafgreen26** [comment] 2018-06-03 02:42
I don't know if this helps, but this problem is also present in Themely and 3DSThemeManager as well. Maybe looking at their source codes might provide some insight.

**Comment by TurdPooCharger** [comment] 2018-06-04 09:10
@Leafgreen26, there's a workaround in getting sleep mode to work.

Press the (HOME) button at least once before clamming the 3DS. This should allow you to wake it back up with Anemone and not blank screens. You can press the (HOME) buttons and and put the 3DS to sleep as many you want for that session.

However, if you switch over to ThemePlaza mode, your 3DS will finally fulfill your request in permission to return to HOME Menu. If you return to using Anemone, switch back to regular Theme mode, and put the 3DS to sleep without pressing (HOME) button again, you get the blank wake up bug.

The problem isn't unique to Anemone as TIKdevil and TIKsweep are two other homebrews with disabled (HOME) button sharing this bug. They, too, can be temporarily remedied with pre-pressing home button trick.

**Comment by Oreo639** [comment] 2020-01-31 06:09
Actually, just curious if the issue still exists now that home button blocking is officially in libctru.

**Comment by Helloman892** [comment] 2020-06-03 20:39
Closing as I cannot reproduce this in the latest commit either.

**Closed by Helloman892** 2020-06-03 20:39 UTC
Labels: bug
