### ISSUE TITLE
Anemone3ds Crashes On Startup

### ISSUE THREAD

**Issue by PlantBeatdown** [astronautlevel2/Anemone3DS#214] opened 2020-03-29 08:40 UTC
I downloaded a recently theme from the in-app browser. I had done this many times before and had encountered no problems. After downloading the theme the 3ds immediately threw an Arm9 data abort exception at me. When I rebooted the system and tried to go back into Anemone3ds, the same thing happened after the 'Loading themes' message popped up. I've tried reinstalling the current version of Anemone3ds and the previous version, deleted the "Anemone3ds" folder inside the "3ds" folder, and deleted "0000008f" and "000002cd" from the "Nintendo 3ds" folder, yet nothing has changed. I'm using an O3dsXL with Luma 9.1, and the app previously had shuffle on but had encountered no problems when downloading themes from the in-app browser while shuffle was active.

**Comment by astronautlevel2** [comment] 2020-03-30 21:53
Hello,

This sounds like a corrupt or invalid theme was downloaded - can you describe which theme you downloaded which caused these issues, as well as upload your themes folder?

**Comment by PlantBeatdown** [comment] 2020-04-01 22:23
I don't remember the exact theme, and I'm not sure which folder holds the themes;;

**Comment by astronautlevel2** [comment] 2020-06-12 13:57
Hi, is this still an issue on the latest build? Can you try this CIA for me? Thanks!

![canvas](https://user-images.githubusercontent.com/7305572/84510439-1d4d5a00-ac93-11ea-8f7d-c06634691344.png)

**Comment by astronautlevel2** [comment] 2020-06-17 19:27
Closing as I cannot reproduce and OP hasn't gotten back to me.

**Closed** 2020-06-17 19:27 UTC
Labels: bug, could not reproduce
