### ISSUE TITLE
Sort list s alphabetical order

### ISSUE THREAD

**Issue by Ryumarubr** [astronautlevel2/Anemone3DS#33] opened 2017-09-03 17:08 UTC
I do not know if it was already suggested, you could sort the list alphabetically.

**Comment by ZetaDesigns** [comment] 2017-09-03 17:34
Make Key_R sort and unsort the list again maybe?

**Comment by astronautlevel2** [comment] 2017-09-16 01:57
Duplicate of #14

**Closed** 2017-09-16 01:56 UTC
Labels: duplicate, enhancement
