### ISSUE TITLE
QR scanner failing to initialize on old 3ds and freezes console

### ISSUE THREAD

**Issue by David-Mayes** [astronautlevel2/Anemone3DS#226] opened 2020-07-02 16:25 UTC
I recently installed Anemone on two o3ds but the QR Scanner fails to run properly on both. There is about 3 different things that can happen on each reset.

1. While it still says "Loading QR Scanner", the camera turns on but nothing changes on screen. Then you are stuck until you press the R button again, cancels the scanner which but show the camera image for a split second.

2. The above happens, but leaving it for too long will cause the entire console to freeze forcing a reboot via the power button.

3. It works as intended.

This happens to both my consoles. They both have the same release of Anemone3DS, which I downloaded here about two days ago.

**Comment by Helloman892** [comment] 2020-07-17 04:50
Hi, sorry it took so long to get to this: could you try this build? 
![image](https://user-images.githubusercontent.com/1565516/87749731-65f7b600-c7f1-11ea-82db-03eff5fe32d3.png)

**Comment by David-Mayes** [comment] 2020-07-17 22:18
Thanks for looking into this, I've just installed that version and it
worked perfectly the first time, but on subsequent tries of the app I've
been having the same issues.

Not sure what's causing it, it might just be my 3dses. Still, I don't use
this application that much so don't worry yourself too much about fixing it
as fast as possible.

**Comment by llaver** [comment] 2020-07-21 04:38
Having the same issue.

**Comment by ayreon** [comment] 2020-07-26 12:10
I have the same issue on N3DSXL.

The first scan was successful, but every attempt after that resulted in a freeze. I had to restart the console.

**Comment by GingkathFox** [comment] 2020-07-26 15:50
can confirm, havent been able to get the qr scanner working

Anemone v2.1.0

Luma v10.2

3ds v11.10.0-45U

**Comment by astronautlevel2** [comment] 2020-07-27 13:57
Duplicate of #189

**Closed by astronautlevel2** 2020-07-27 13:57 UTC
