### ISSUE TITLE
The controls list on the upper screen shouldn't list the Select button as "-"

### ISSUE THREAD

**Issue by StateOfException** [astronautlevel2/Anemone3DS#94] opened 2017-10-07 02:27 UTC
As things stand, the instructions on the top screen include a reference to a "-" button- no such button exists on the 3DS, nor is the Select button labelled with a "-" design. 

The only way a user could infer the button icon's meaning is if they're already familiar with Wii Classic/Wii U controllers- and there's no guarantee of that. It's absolutely not a universally acknowledged (or even recognisable) symbol for the Select button- a large number of users will probably be confused by it.

It should probably be changed to something more suitable- it's pretty awkward UI design as things stand. I expect most users will, as things stand, have to figure out its meaning through trial and error- chances are, a lot of people will hit Start the first time they try it, exiting the program- it's not great, discoverability-wise.

**Comment by ZetaDesigns** [comment] 2017-10-07 11:01
Well, that's the only select button the 3DS' system font has (https://www.3dbrew.org/wiki/System_Font). Writing something like "select" takes much more space.

Also a duplicate of #86

**Comment by astronautlevel2** [comment] 2017-10-07 13:24
If someone draws a select button glyph I'd be more than happy to use it.

**Closed** 2017-12-08 21:52 UTC
Labels: enhancement, help wanted
