### ISSUE TITLE
The QR Scanner crashes

### ISSUE THREAD

**Issue by AMonreale** [astronautlevel2/Anemone3DS#224] opened 2020-06-26 21:07 UTC
Hi,

I just installed Anemone on my 3DS XL and it crashes everytime i launch the QR Scanner, I have to force the shutdown of the console.

**Comment by Oreo639** [comment] 2020-06-26 23:04
Are you sure this is a crash and not a lockup?
(See: https://github.com/astronautlevel2/Anemone3DS/issues/189 )

If you are sure it is a crash, does this crash occur on *hax or Luma?
If *hax, which entrypoint? If Luma, is there a crash log?

**Comment by sekushi18** [comment] 2020-06-27 02:11
Hello,

 I'm also having this problem from luma 3days after finish hacking. When i try to preview a theme, Then go to scan a qr code after returning from the preview the qr locks then displays arm 11 handler crash. If you can tell me where the crash log is i can send it and see if i can get help fixing my qr code scanner that now never loads up till i cancel the scan.

using a new 3ds xl pikachu.

**Comment by AMonreale** [comment] 2020-06-27 09:26
> 
> 
> What version are you using?
> 
> Are you sure this is a crash and not a lockup?
> (See: #189 )
> 
> If you are sure it is a crash, does this crash occur on *hax or Luma?
> If *hax, which entrypoint? If Luma, is there a crash log?

Maybe it was a lockup, but oddly it started working today. I didn't do anything, just turned off the console yesterday night and turned on today.

**Comment by Oreo639** [comment] 2020-06-27 20:04
> I'm also having this problem from luma 3days after finish hacking. When i try to preview a theme, Then go to scan a qr code after returning from the preview the qr locks then displays arm 11 handler crash. If you can tell me where the crash log is i can send it and see if i can get help fixing my qr code scanner that now never loads up till i cancel the scan.

The crash dumps should be in /luma/dumps. You can know which dump by getting a crash, then press a. (It will say where the dump saved to).

Please do it in a new issue. (since your issue is different than the OP's afaict)

**Comment by astronautlevel2** [comment] 2020-07-01 17:41
Dupe of #189

**Closed by astronautlevel2** 2020-07-01 17:41 UTC
