### ISSUE TITLE
Anemone3DS cia stuck on loading

### ISSUE THREAD

**Issue by fervorous** [astronautlevel2/Anemone3DS#215] opened 2020-05-01 13:40 UTC
I am on the latest Luma3ds, device is New3ds running latest firmware, Anemone3DS that I installed through FBI will be stuck on "Loading... please wait" I tried version 2.10, 2.01, 1.30 all stuck on boot. I can run it fine by homebrew (3dsx file)

**Comment by astronautlevel2** [comment] 2020-06-12 13:56
Hi, is this still an issue on the latest build? Can you try installing this CIA for me to give it a try? Thanks!




![canvas](https://user-images.githubusercontent.com/7305572/84510377-0ad32080-ac93-11ea-8f41-47dfe12f8132.png)

**Comment by astronautlevel2** [comment] 2020-06-17 19:27
Closing issue as I cannot reproduce on v2.1.0 and OP hasn't gotten back to me.

**Closed by astronautlevel2** 2020-06-17 19:27 UTC
Labels: bug, could not reproduce, further research needed
