### ISSUE TITLE
Activating the QR Scanner causes it to freeze

### ISSUE THREAD

**Issue by ghost** [astronautlevel2/Anemone3DS#189] opened 2018-08-29 05:25 UTC

**Comment by astronautlevel2** [comment] 2018-09-03 18:15
I need more information.

1. What version of Anemone3DS are you using? This is in the bottom left of the main menu.
2. Are you using CFW or just homebrew? If CFW, which one?
3. What does the screen look like when it freezes?

**Comment by Leafgreen26** [comment] 2018-09-03 18:30
New 3DS, 11.8. This is in the beta version of anemone that was recently released. I am using Luna 9.1 CFW. When it freezes it just stayed on the Activating WE Scanner screen

**Comment by jkh970325** [comment] 2018-09-22 01:55
Same here. I thought I was the only one. Has this been solved yet? Once I press R, it just says "Loading QR Scanner..." I have 11.8 firmware. Old 3DS. Anemone v.2.1.0-b.

**Comment by Fabry200** [comment] 2019-05-11 09:12
how to downgrade?

**Comment by Helloman892** [comment] 2019-05-11 23:50
Downgrade simply by installing the previous version in FBI.

As a side-note, please don't necropost in six-month old issue threads without anything to contribute. :)

**Comment by gmondragon** [comment] 2019-12-11 22:11
Hi all. It worked for me by turning off WiFi, then I activated the camera to scan the QR. With the camera on, enable Wi-Fi again. So I prevented it from freezing.

**Comment by Helloman892** [comment] 2020-06-11 23:16
As far as we know, this doesn't happen in the latest commit (and hence the next release). Closing unless someone can reproduce.

**Comment by sfinam** [comment] 2020-06-19 20:48
Still freezes for me on 2.1.0, Luma 10.1.3, old 3DS.
Screen says  "Loading QR Scanner..."

**Comment by xpirad** [comment] 2020-06-22 13:12
> Still freezes for me on 2.1.0, Luma 10.1.3, old 3DS.
> Screen says "Loading QR Scanner..."

i have the same issue

**Comment by astronautlevel2** [comment] 2020-06-22 13:25
@xpirad can we get more information, such as console model (old 3ds vs new 3ds)?

**Comment by astronautlevel2** [comment] 2020-06-22 13:28
@xpirad can we get more information, such as console model (old 3ds vs new 3ds)?

@sfinam Does gmondragon's suggestion of turning off WiFi work?

**Comment by xpirad** [comment] 2020-06-22 14:00
hi, i'm using new 3dsxl

**Comment by sfinam** [comment] 2020-06-22 15:13
@astronautlevel2 I've tried to do it but I'm not sure how. When I disable wifi it says that I need Internet to scan qr codes and won't open the scanner. If the scanner is open, I can't disable wifi anymore as the system is frozen.

**Comment by astronautlevel2** [comment] 2020-06-22 15:32
That's what I figured would happen. Would you mind giving this build a try and letting me know what happens, @sfinam? I'm expecting it to either work or give an error message, but not hang. If it does hang then I'm looking into the wrong thing.


![image](https://user-images.githubusercontent.com/7305572/85306161-1802c300-b47c-11ea-823b-380282abfdb9.png)

**Comment by sfinam** [comment] 2020-06-22 22:12
@astronautlevel2 First time after start is stuck on  "Loading QR Scanner..." for a while, but wifi led blinks and I can disable wifi. This does nothing though. If I wait around two minutes it stops blinking (just green) and not sound anything). I've tried randomly pressing buttons and camera turned on after pressing A. First time I've tried scanning a code from themeplaza it crashed prompting me to press A to save crash dump, but I wasn't quick enough - the system turned off. Second and all the following times it worked though. I still had to press buttons to get it to start, but after it starts once it can turn on instantly afterwards, and I was able to download themes without it crashing.

**Comment by astronautlevel2** [comment] 2020-06-22 22:14
Huh, you shouldn't have to press buttons for it to work. Does pressing A to work on the v2.1.0 release, or does it only work on that version I posted in the comment above?

**Comment by sfinam** [comment] 2020-06-22 23:02
I've downloaded 2.1.0,installed it over your build, got it to hang once and no buttons were responding, but I was able to open Rosalina menu and it got unstuck somehow. After this I can't get it to freeze - it loads for a few seconds and launches normally, even after reboot.

**Comment by astronautlevel2** [comment] 2020-06-24 17:22
Thanks, I'm not sure what else I can do to fix this, it's likely an issue with something beyond our capability on the 3DS w/r/t thread creation. I'm going to close this and put a message in the app to press A if it hangs. Thanks for your help!

**Comment by CubeBag** [comment] 2020-07-04 06:35
I also had this issue with a newly modded new 2ds xl. If it helps, my fix was to remote install any splash (the globe with the mouse pointer that brings up "Downloading splash list, please wait...") and then the QR scanner worked in the splashes tab. I downloaded a theme the same way to see if it would work again, but the theme QR scanner **did not** work. In fact, the splash QR reader broke. Also if it helps, I'm running the 3dsx version.

**Comment by xpirad** [comment] 2020-07-04 07:16
@astronautlevel2  Could you release a new build?

**Comment by astronautlevel2** [comment] 2020-07-06 17:21
I'm not sure what build you'd want me to release, the build from the QR code in this issue is the most recent work I've done on this.

**Comment by Agilo3** [comment] 2020-07-10 01:27
2.1.0 (Revival Edition), installed with FBI through QR code listed in release page, still freezes the app. Quite annoying.

**Comment by Demarah** [comment] 2020-07-14 00:49
QR scanning worked for me first but after a crash it always got stuck on "Loading QR Scanner...". In my case it helped to start the Nintendo 3DS-camera app and take a photo. After that in Anmeone the "Loading QR Scanner..." message disappeared after a few seconds, I got the camera preview and QR codes were recognized again.

**Comment by astronautlevel2** [comment] 2020-07-27 13:58
Seems as if the latest commit may not fix this, re-opening.

**Comment by astronautlevel2** [comment] 2020-07-27 13:59
@Agilo3 can you try the QR code listed above? Thanks.

**Comment by 3ooo** [comment] 2020-08-23 18:30
sorry if this is no help, but i installed cfw on a new 2dsXL and a new 3dsXL in the same day in the same way. both 11.13, but the new 2dsXL's qr scanner works perfectly on anemone. the 3ds isn't the same story. i have 2.1.0 on both, but installed the qr version from this thread on the 3ds before typing this. the qr scanner freezes the 3ds so badly that i need to power it off if i don't spam buttons to make it stop trying to scan.

note: spamming b upon beginning scan will abort the scan, but continue the process of scanning. i got my themes by aiming the camera at the qr code and spamming b every time i scanned until it registered the code.

**Comment by Pablokiryu** [comment] 2020-09-02 22:29
I am also experiencing this issue on my o3ds firm 11.13.0-45u. latest Luma .
Anemone latest stable v. 2.1.0 
on my N3DSXL, same firmware/luma/Anemone versions it works fine.

**Comment by rly907** [comment] 2020-09-03 02:58
> I am also experiencing this issue on my o3ds firm 11.13.0-45u. latest Luma .
> Anemone latest stable v. 2.1.0
> on my N3DSXL, same firmware/luma/Anemone versions it works fine.

Exact same story for me, latest Luma and anemone, won't work on o3ds, but will on n3ds

**Comment by Zeynex** [comment] 2020-09-04 12:54
I just scaned an qr code over the wifi on off methode since it will also freeze for me and then i wanted to scan another one it startet the camera and reconized the qr code and afterwards this happend 
![20200904_145125](https://user-images.githubusercontent.com/19517770/92241435-80c7dc00-eebe-11ea-9997-1dfdc0f7fc79.jpg)

**Comment by Trixelit** [comment] 2020-09-05 23:59
I'm currently having the same problem, New 2DS XL. Latest version of Luma3DS and v2.1.0 of Anemone. I hit R and it hangs on loading QR scanner

**Comment by xXK1NGxR3APERXx** [comment] 2020-09-08 03:18
> QR scanning worked for me first but after a crash it always got stuck on "Loading QR Scanner...". In my case it helped to start the Nintendo 3DS-camera app and take a photo. After that in Anemone the "Loading QR Scanner..." message disappeared after a few seconds, I got the camera preview and QR codes were recognized again.

I tried this method, only had to take one photo. Closed camera app then anemone QR scanner worked fine.

**Comment by staehle** [comment] 2020-09-11 21:11
> 
> 
> > QR scanning worked for me first but after a crash it always got stuck on "Loading QR Scanner...". In my case it helped to start the Nintendo 3DS-camera app and take a photo. After that in Anemone the "Loading QR Scanner..." message disappeared after a few seconds, I got the camera preview and QR codes were recognized again.
> 
> I tried this method, only had to take one photo. Closed camera app then anemone QR scanner worked fine.

I have this same issue on New 3DS 11.13, Luma, Anemone 2.1.0.

King's solution works -- Just take a picture with the system camera first, then load Anemone, and the QR scanner will then work

**Comment by astronautlevel2** [comment] 2020-12-23 22:40
Can anyone test again on this build? It may fix certain camera issues.
![image](https://user-images.githubusercontent.com/7305572/103041937-e1e6ee80-4545-11eb-88c1-3426c2155e8d.png)

**Comment by Zeynex** [comment] 2021-01-01 19:44
> Can anyone test again on this build? It may fix certain camera issues.
> ![image](https://user-images.githubusercontent.com/7305572/103041937-e1e6ee80-4545-11eb-88c1-3426c2155e8d.png)

After 2 scans i can say it works for me at thr moment without crashes and needing to turn off the wifi

**Comment by Zeynex** [comment] 2021-01-01 19:51
> > Can anyone test again on this build? It may fix certain camera issues.
> > ![image](https://user-images.githubusercontent.com/7305572/103041937-e1e6ee80-4545-11eb-88c1-3426c2155e8d.png)
> 
> After 2 scans i can say it works for me at thr moment without crashes and needing to turn off the wifi

It dif crash after updating luma and restarting the 3ds at the restart through i dont know if it had to do that i already had the version installed [excpect the one on the sd hence why i did it since i dont remember which version i did sd less or with sd so it also could be that and i hope my 3ds is fine since i have ben having issues for some time now i think ... unsure] or with anemone since i didnt reboot after the update

**Comment by astronautlevel2** [comment] 2021-01-02 05:01
Positive confirmation from multiple sources now that if the freeze occurs, opening the official 3DS camera application fixes it. Going to leave this open in case there's new evidence in the future regarding why this causes it but for right now I'm considering this issue solved.

**Comment by Helloman892** [comment] 2024-02-23 18:55
Closed as stale.

**Closed by Helloman892** 2024-02-23 18:55 UTC
Labels: bug, wontfix, implemented/solved
