### ISSUE TITLE
Shuffle Themes Stopped Looping Infinitely

### ISSUE THREAD

**Issue by greenDarkness** [astronautlevel2/Anemone3DS#65] opened 2017-09-07 06:09 UTC
Hello, recently a friend and I installed the following themes using Anemone:
```
1532 - Pokemon - Pokemon Gold Version
1533 - Pokemon - Pokemon Silver Version
```
They were looping fine for a while, but after we added around 4 themes to shuffle the bgms stopped playing continuously. We set it back to just the two themes being shuffled, but now the themes no longer loop infinitely. 
Has this happened to anyone else? Is there anything I can do to trouble shoot this issue? I'm using version  v1.1.1. I'd also like to add that loop works fine when installing a single theme.
Thank you for taking the time to read this, and for all your work with Anemone/Luma nitelies.

**Comment by Helloman892** [comment] 2017-09-07 08:36
Refer to #28, although I'll keep this open as it's more specific.

In regards to your problem, Looping Audio Converter seems to fix this in some cases, but sometimes it doesn't. For now, this a bug that isn't your fault.

**Comment by greenDarkness** [comment] 2017-09-07 11:08
@Helloman892 Reading over it now. Didn't mean to duplicate report.

Is there anyway you could link me to that, please? 
Glad to hear it wasn't something me and my friend have done. Hopefully the problem can be solved. 
Thanks again!

**Comment by Helloman892** [comment] 2017-09-07 12:20
https://github.com/libertyernie/LoopingAudioConverter/releases

~~google~~

**Comment by papermario69** [comment] 2017-09-08 01:07
I have the same issue. Do I put LAC in the root of my SD card or in the 3ds folder?

**Comment by greenDarkness** [comment] 2017-09-08 03:59
Thank you! Trying it now.

**Comment by greenDarkness** [comment] 2017-09-08 04:05
@papermario69 LAC is a Program for your computer. It can be used to edit the bgm.bcstm file in your Theme to make it loop.

**Comment by Helloman892** [comment] 2017-09-08 09:32
I [personally] still don't know why this happens, but my best guess is that it's something to do with the way we write BGM to the theme extdata. 

It's good that it fixes the BGM that we broke [☹️] but at least the fact that shuffle breaks it is consistent. We'll get it fixed between now and 1.2.0.

**Comment by greenDarkness** [comment] 2017-09-08 12:50
Yeah, at first I thought it might just be that the themes we were installing were not official (My friend and I tried making a few); because initially he was able to install the two themes I mentioned earlier with shuffle and it did not break the looping audio (Granted the bgm.bcstm file was the same for both themes).

After that success we tried to install 8 shuffle themes with the same bgm.bcstm file, and shuffle still broke the audio. After which we were no longer able to get the first two official themes to loop.

Yeah for sure. Can't wait for the next release! I know that Anemone is on it's way to being the indisputable best theme installer for the 3ds. It's got all the proficiency of the other installers, ~~without all the malware~~. ;)

**Comment by Helloman892** [comment] 2017-09-08 12:59
;)

**Comment by ValiantBlade** [comment] 2017-10-17 22:50
Yeah some themes I've been using that I know loop properly have been breaking this way. There's definately a bug with the shuffle implementation.

**Comment by Helloman892** [comment] 2017-10-18 10:54
@ValiantBlade It's being Worked On:tm:. astro and I both have a lot on our plate at the moment, but we're getting there.

**Comment by EarthboyBebop** [comment] 2017-12-03 19:10
@Helloman892 Hello, just curious if you guys have made any headway concerning shuffling BGM? Set up anemone last night, and I'm loving it thus far.

**Comment by Helloman892** [comment] 2017-12-03 20:51
Shuffling BGM hasn't even been considered yet - make your own issue about that suggesting what exactly you mean by it and why. It doesn't pertain to the topic of this thread.

**Comment by EarthboyBebop** [comment] 2017-12-03 20:56
@Helloman892 Sorry, I guess I wasn't clear enough. I'm talking about the BGM that doesn't loop infinitely when using shuffled themes. My themes all shuffle, but the music stops after a minute or so.

**Comment by Helloman892** [comment] 2017-12-03 21:56
Ah - well, we haven't quite nailed down the cause, and frankly we have bigger fish to fry at the moment.

This issue will remain open until the problem is resolved, not to worry.

**Comment by Jojokesuke** [comment] 2017-12-17 04:09
I've determined a common element. The themes I made that loop from the very beginning to the very end of the bgm seem to be cut off just before the loop when on shuffle. The themes I made that loop from one point of the bgm to another (not at the very beginning or end) loop fine on shuffle.

Not sure if that helps but, I thought I'd at least mention it.

**Comment by CecilFF4** [comment] 2017-12-31 21:04
Just confirming that this issue is still present on 1.3.0 for apparently every shuffle theme bgm that has a loop point set.

**Comment by ricksee** [comment] 2017-12-31 21:41
Can also confirm this happens on my 11.2 3DS. BGM either stop looping after the song is done or stop/cut off at around the 1 minute interval.

**Comment by Helloman892** [comment] 2018-01-01 18:34
@CecilFF4 @ricksee
We know this is an issue, we've known it's been an issue for months, and we haven't done anything to fix it because we don't know what the issue is. I know you both mean well, but please (and this is to anyone looking at the issue) don't revive the thread just to tell us that it still happens. 

We will close this issue when it is fixed.

**Comment by CecilFF4** [comment] 2018-04-25 05:54
Sorry if this is not useful for this issue, but my tests revealed that the problem for this issue may lie in the bodycache_rd file's construction. I know it should be as simple as just combining all the body_lz.bins together to make it; however, the hex reveals a discrepancy (between an official rd and an anemone-created one) starting at 0x00040000 (20% of the body_lz.bin size). In particular, my test theme's body_lz.bin is very different than the extracted body_lz.bin (as taken from the anemone-created bodycache_rd) starting at that location.

To do my tests, I created an HTT theme package containing two test themes, then copied the theme information. Did the same after using Anemone for those same themes. Did a comparison of the hex in the un-extracted 000002cd files (including the redundant files) to help narrow down the culprit. Then swapped out the different files in the Anemone install to see if any swaps fixed the issue (they didn't). There was actually no change in the behavior of the theme until I swapped the bodycache_rd file, though the swap just reset the theme manager completely rather than cause the bgm to loop correctly.

**Comment by TurdPooCharger** [comment] 2018-05-05 11:07
I found a way to get shuffled themes to loop with BGM. Will write and post details of this later. Please be advised the CHMM2 theme manager will be involved in this write up, which is also affected by this bug.

**Comment by TurdPooCharger** [comment] 2018-05-08 16:35
### A Terribly Written Introduction. An Intro nonetheless.
Ugh. So I gathered all the data I could find to present in this report, and I’m having awful writers block in how best to put the results into words.

I guess the first thing I’ll talk about is that I’ve been following your Github and GBAtemp thread for a while now. Every new release came with the inevitable disappointment of finding out the blue branded theme manager still had this bug. It’s just weird seeing something that used to work stay broken for that long.

It’s not like we can blame you devs for something most people couldn’t begin to fathom what the problem was in those lines of code. At one point, I began to wonder if the 3DS firmware updates changed how themes fundamentally work and if you guys were stumped by something that couldn’t be programmed around. 

If the experts who specialize in this particular area of 3DS homebrew didn’t know where the problem lies, what gives any regular Joe Shmoe the right to complain about this? You don’t like it, then go fix it yourself by making your own theme manager. Can’t do that you say? Use a different competing theme manger that doesn’t have this bug. Oh wait, that’s right. Too bad for you and me (figuratively), **ALL three theme managers share this bug.**

Or so the saying goes.

### When expectation doesn’t meet reality. In a positive way for once. 
During one of my moments of curiosity, I decided to tinker around with the other two theme managers. I wanted to know what they were like despite the two mostly falling out of favor with the general 3DS users. Even though their developments have halted, were Rinnegatamante and Erman1337 creations considered too outdated for today’s 3DS homebrew usage? That question will respectfully remain unanswered. :smile: 

Eventually, another question came to mind. Do CHMM2 and Themely _really_ share the same bug with Anemone3DS?

Because I had all three theme managers installed at the same time at one point (strange, right?), my initial assessment was that the BGM loop bug did indeed affect all three apps.

What was weird was that the BGM bug appeared in an inconsistent manner whenever switching between these three. At the time this was noticed, I paid little heed to this observation as there was another more pressing matter being dealt with on Anemone3DS. After that issue was resolved, all efforts were put on hold with anything related to troubleshooting 3DS bugs. I went on break so to speak but not for long.

Eventually, I relooked into this BGM loop bug by first approaching the problem by hex studying the theme extdata files created by Anemone. That method came to a dead end, yielding nothing conclusive or understandable.

Afterwards, I tried several combinations of shuffle installing themes using Anemone, CHMM, Themely, stock 3DS theme manager, Nintendo Theme Shop, theme DLC acquired by _that other shop_, and repetitively deleting the theme extdata folder before stumbling upon a consistent manner of producing themes with looping BGM. Several refinements later, I managed to pinpoint a suspect cause to this bug.

Here’s the bad news. Anemone3DS, the bug is yours alone. No ifs and buts. All you.

The reason CHMM and Themely _appeared_ to have this bug is that Anemone was involved beforehand in modifying the theme extdata. Whenever the theme extdata was deleted, rebuilt from scratch, and those two did their magic by themselves without Anemone in the mix, the bug goes away. Shame on me and anyone pinning that blame on them. 

Here’s the good news. The bug is fixable because we now know where to look! Here’s how that conclusion was reach.

### The boring stuff. The hard side. 
I think by now, you guys are familiar enough with my 3DS build. I’m mentioning this again because we want no details to be missed. Also, I want others to retest this on their end as peer review.

**These steps were taken before creating the setup below:**  
- Deleted HOME Menu Themes DLC from freeShop
- Deleted official themes downloaded from Nintendo Theme Shop

**Hardware Setup**  
- New 3DS XL (USA model)
- 4GB Lexar micro SD card (originally included)
- FAT32 & 32 KB allocation (Windows Quick Format)
- Barebones files on SD card (those needed below)
- Luma3DS v9.0
- GodMode9 v1.6.3
- Rosalina injected Homebrew Launcher (AR Games)
- FBI v2.5.0 (.3dsx) – for CIA installer
- Cthulhu v1.3.3 (.3dsx) – for initial cache clearing everything
- no 3DS games 
- no homebrew titles (except the 3 below)
- no system app injections
- no DSiWare (except TWLoader dependencies)
- no inserted cartridge
- Title tickets and keys left alone (too messy reinstalling)
- Themes folder with selected 10 themes (see below)

**Installed on HOME Menu:**  
- Anemone3DS_v2.0.0a-95d8808a (3uYGM) – [nightly build with fixed logo]
- CHMM2_v.2.8
- Themely_v1.3.1-i1

![theme shootout](https://user-images.githubusercontent.com/35666439/39767923-dcace51c-52b5-11e8-9bac-5a10be01b0ad.png)

### More Boring Stuff. The Soft Side.
Our testing will compare the output theme extdata files between the three managers.

You will need the program **Duplicate Cleaner Pro** in order to carry out the tests described here. This software does file checking by hash comparison. It checks for similarities between files as low as 60%.

![duplicate cleaner pro](https://user-images.githubusercontent.com/35666439/39767981-0d234236-52b6-11e8-97ef-1a587ff63494.png)

The ten themes that were used are all USA region versions. They are:

- 042 - Pokemon - Onemuri Pikachu
- 084 - Zelda - Dire Moon
- 085 - Zelda - Gold Edition
- 181 - Zelda - Brave Trio
- 300 - The Legend of Zelda 30th Anniversary
- 307 - TLoZ - Breath of the Wild - Wide World
- 308 - TLoZ - Breath of the Wild New Adventure
- 321 - Pokemon - Look Upon the Stars
- 326 - Pokemon - Pokemon Gold Version
- 327 - Pokemon - Pokemon Silver Version

![ten themes 1 2 3 order big](https://user-images.githubusercontent.com/35666439/39768085-51e65cd2-52b6-11e8-8c5f-61c3eb785e51.png)

To carry out these tests, the instructions listed here need to be followed to the dot. No half-assies, or you won’t get clean results. **Do NOT gimp and take shortcuts.**

### TEST No.1 – One Theme

1. In GodMode9, delete the current **000002cd** theme extdata folder found at:
`0:/Nintendo 3DS/<ID0>/<ID1>/extdata/00000000/`

2. Restart the 3DS. At the top left corner, go to **HOME Menu Design** and then **Change Theme**. Allow the theme extdata to be rebuilt.

![rebuild theme extdata](https://user-images.githubusercontent.com/35666439/39768371-241f9d80-52b7-11e8-8288-e7fb2f412ae4.png)

3. Return to GodMode9 and make a backup of the newly recreate **000002cd** folder. Use **Copy to 0:/gm9/out** and rename that copy to something like **000002cd (original)** .

**Explanation:* This **000002cd (original)** folder will be cross compared against those modified by Anemone3DS, CHMM2, and Themely. This folder will also serve as a seed bank for the test runs to minimize noisy data. Whenever the 3DS rebuilds **000002cd** from scratch, there are slight variations within the same files between each set. Every time you do a new test case, the **000002cd (original)** has to replace those rebuilt **000002cd**.

4. Your **000002cd** folder should only have (5) files at this moment:
- 000000001
- 000000002
- 000000003
- 000000004
- 000000005

If you have any other files, you created a shuffled theme extdata folder. Please redo steps 1-3 as the first test will only involve single theme testing. We will do shuffle themes in later tests.

5. Reset the 3DS and launch Anemone. Do a single theme install of:

- 042 - Pokemon - Onemuri Pikachu

![pikachu](https://user-images.githubusercontent.com/35666439/39768548-a10ff52e-52b7-11e8-8b87-6494edefbd3f.png) 

The reason why this theme was chosen was for its short loop interval.

6. Turn off the 3DS with the (Start) button. Go to GodMode9, copy the **000002cd**, and rename that copy as **000002cd (Anemone3DS)**.

7. Restart the 3DS and observe the behavior of the installed theme. It has working BGM loop.

8. Go back to GodMode9 and delete **000002cd** as described in step 1.

9. Restart the 3DS and recreate that folder as described in step 2.

10. Go back to GodMode9 again and delete the recreated **000002cd** folder. Replace that folder with the one sourced from **000002cd (original)**.

11. Repeat steps 5-10 for CHHM2 and Themely to obtain **000002cd (CHMM2)** and **000002cd (Themely)** folders.

12. Cross compare all (4) sets of folders against each other using **Duplicate Cleaner Pro**. Here are the results.

![1 themes comparison](https://user-images.githubusercontent.com/35666439/39768752-3773e1a6-52b8-11e8-8660-234d58c0a42a.png)

No surprises here. All three theme mangers can handle installing one theme where BGM looping works. A neat observation is that Anemone3DS handles single theme installation exactly like Themely as seen in the **00000003** file.

### TEST No.2 – Two Themes

Here’s where things gets a little more complicated. The steps listed in **TEST No.2** should NOT be confused for those in **TEST No.1**. There are some additional steps that are a little different. You should treat the **000002cd** folders in **TEST.1** separate from those produced in **TEST No.2**.

1. In GodMode9, delete the current **000002cd** theme extdata folder found at:
`0:/Nintendo 3DS/<ID0>/<ID1>/extdata/00000000/`

2. Restart the 3DS. At the top left corner, go to **HOME Menu Design** and then **Change Theme**. Allow the theme extdata to be rebuilt.

![rebuild theme extdata](https://user-images.githubusercontent.com/35666439/39768371-241f9d80-52b7-11e8-8288-e7fb2f412ae4.png)

3. Go to **Shuffle Favorites** and select all (5) basic color themes in descending order of Red, Blue, Yellow, Pink, and Black. Press (Y) to install shuffle. Allow the theme extdata to update.
 
![update theme extdata](https://user-images.githubusercontent.com/35666439/39768985-d7e3019e-52b8-11e8-9448-1f3dc54d586f.png)

4. Go back to **Change Theme** and select **Do not use a theme**.

5. Return to GodMode9 and make a backup of the newly recreate **000002cd** folder. Use **Copy to 0:/gm9/out** and rename that copy to something like **000002cd (original - two)** .

6. Your **000002cd** folder should have these (16) files:
- 0000000a
- 0000000b
- 0000000c
- 0000000d
- 0000000e
- 0000000f
- 00000001
- 00000002
- 00000003
- 00000004
- 00000005
- 00000006
- 00000007
- 00000008
- 00000009
- 00000010

7. Reset the 3DS and launch Anemone. Do a shuffle theme install with:

- 042 - Pokemon - Onemuri Pikachu
- 084 - Zelda - Dire Moon

![two themes pikachu zelda](https://user-images.githubusercontent.com/35666439/39769125-475f4514-52b9-11e8-8285-df9532332fdd.png)

It has to be those two specific themes selected in that exact order. You have to select Pokemon first and Zelda second. **DO NOT SUBSTITUTE FOR ANY OTHER THEMES!!!** I’ll later explain why this is required in **TEST No.3 – Ten Themes**. Just know that selection order will affect results, especially in CHMM and Themely. Remember, pick Pikachu as first (1st) and then Link as second (2nd).

8. Turn off the 3DS with the (Start) button. Go to GodMode9, copy the **000002cd**, and rename that copy as **000002cd (Anemone3DS - two)**.

9. Restart the 3DS and observe the behavior of the installed themes. BGM looping does not work for Anemone.

10. Go back to GodMode9 and delete **000002cd** as described in step 1.

11. Restart the 3DS and recreate that folder as described in steps 2-4.

12. Go back to GodMode9 again and delete the recreated **000002cd** folder. Replace that folder with the one sourced from **000002cd (original - two)**.

13. Repeat steps 7-12 for CHHM2 and Themely to obtain **000002cd (CHMM2 - two)** and **000002cd (Themely - two)** folders. You should notice these two have working BGM loop.

14. Cross compare all (4) sets of folders against each other using Duplicate Cleaner Pro. Here are the results.

![2 themes comparison](https://user-images.githubusercontent.com/35666439/39769261-ab5cfc64-52b9-11e8-9139-fde00edacac2.png)

What should catch your immediate attention is that there’s a 2% change in Anemone’s **00000001** file not seen in CHMM2 and Themely. Another neat fact is that CHMM2 is the most conservative of the three in terms of modifying the theme extdata. In shuffle theme mode, CHMM2 is slight more similar to Themely than Anemone as shown in files **00000007** and **00000008**. The only similarity between Anemone and Themely is again found in **00000003**.

### TEST No.3 – Ten Themes
This test was the hardest to carry out because I soon learned that each theme manager had its own kinks when it came to queuing themes.

Anemone was what I considered the pickiest of the bunch. These ten themes load up alphanumerically by either **info.sdmh** or **name.txt**; it doesn’t matter whichever order the themes are selected because they will install in descending order by their names. I can try installing _Zelda – Gold Edition_ at first (1st) and _Pokemon – Look Upon the Stars_ at tenth (10th). Doesn’t matter. _Gold Edition_ will always go at 10th and _Look Upon the Stars_ at 1st. 

1. Pokemon - Look Upon the Stars
2. Pokemon - Onemuri Pikachu
3. Pokemon - Pokemon Gold Version
4. Pokemon - Pokemon Silver Version
5. TLoZ - Breath of the Wild New Adventure
6. TLoZ - Breath of the Wild - Wide World
7. The Legend of Zelda 30th Anniversary
8. Zelda - Brave Trio
9. Zelda - Dire Moon
10. Zelda - Gold Edition

![ten themes anm order big](https://user-images.githubusercontent.com/35666439/39769443-36134eee-52ba-11e8-9db9-341f01ee3cfd.png)

Themely was just as bad in its own way. Themely also doesn’t allow picking and choosing whichever theme goes in whichever order. The order of installation goes by the name of the individual theme folders. I had to rename those ten folders to match the order as seen in Anemone. These folders were renamed as:

- 001 - U321 - Pokemon - Look Upon the Stars
- 002 - U042 - Pokemon - Onemuri Pikachu
- 003 - U326 - Pokemon - Pokemon Gold Version
- 004 - U327 - Pokemon - Pokemon Silver Version
- 005 - U308 - TLoZ - Breath of the Wild New Adventure
- 006 - U307 - TLoZ - Breath of the Wild - Wide World
- 007 - U300 - The Legend of Zelda 30th Anniversary
- 008 - U181 - Zelda - Brave Trio
- 009 - U084 - Zelda - Dire Moon
- 010 - U085 - Zelda - Gold Edition

CHMM2 was perhaps the most forgiving. Themes are also listed by the order of their folder names, but themes are installed in the order they were chosen. This would have been an extreme hassle had I not already renamed those folders for Themely. As for CHMM2’s implement of shuffle selection, I have less than nice things to say about it.

I won’t bother listing the steps here for **TEST No.3** because they are exactly like those in **TEST No.2**. The results:

![10 themes comparison](https://user-images.githubusercontent.com/35666439/39769538-7a5dd2e0-52ba-11e8-8c2f-da0418d8dee0.png)

By now, you should be really suspicious about that **00000001** file. This test round was a surprise seeing CHMM and Themely outputting identical files for **6-10** and **a-f** [1-2-4-5 weren’t changed]. Of course, we can’t leave out the only difference is the **00000003**, which is still the same between Anemone and Themely.

### TEST No.4 – Two (Official) Themes
I downloaded two free themes from the Nintendo Theme Shop.

- Radiant Historia: Chibi Theme
- Sonic series: 25th Anniversary

I wanted to see how legitimately owned themes are handled with the 3DS official theme manager.

![2 themes 3ds theme manager](https://user-images.githubusercontent.com/35666439/39769617-b05dbd24-52ba-11e8-9203-b18a00c1c58f.png)

### TEST No.5 – Ten (Official) Themes
I download eight more free themes. Themes were alphanumerically rearranged in the selection menu and installed in this order:

- Culdcept Revolt
- Etrian Odyssey V: Beyond the Myth
- Radiant Historia: Chibi Theme
- Radiant Historia: Perfect Chronology
- Shin Megami Tensei IV: Apocalypse
- Sonic Boom™: Shattered Crystal
- Sonic series: 25th Anniversary
- The Alliance Alive Character Theme 1
- The Alliance Alive Character Theme 2
- The Alliance Alive Robbins Theme

![10 themes 3ds theme manager](https://user-images.githubusercontent.com/35666439/39769680-d9095094-52ba-11e8-9596-70419bb7de8a.png)

# What does this mean?
See if you can figure out what's changing the **00000001** file. I don't know how to read source code, so can't go further in helping you guys in that front. The latest CHMM2 is closed source, but the Themely I used is still available here: https://github.com/ihaveamac/Themely/releases

 I can't say for sure it'll fix this BGM loop bug because I've been wrong before in jumping to conclusions. I can only say that I believe with strong conviction that's where the problem lies. Good luck!

**Comment by astronautlevel2** [comment] 2018-05-08 17:10
It's been clear that some data is being changed for unknown reasons; however, this does not help us as we do not edit any files directly, only through the extdata.

**Comment by astronautlevel2** [comment] 2018-05-08 17:51
Seems like the 00000001 file (and the 00000000) represents the VSXE metadata for the theme extdata - would you mind providing the dumps of both the 00000000 and 00000001 file? Ideally unencrypted.

**Comment by TurdPooCharger** [comment] 2018-05-08 18:03
@astronautlevel2, how do I find the **00000000** file? I only see those 16 files within the `0:/Nintendo 3DS/<ID0>/<ID1>/extdata/00000000/000002cd/00000000` folder. I don't know what this DIFF Extraction is in GodMode9. :/

**Comment by CecilFF4** [comment] 2018-05-08 18:07
If these numbered files are in anyway named in a similar fashion to Mii Plaza, then those obfuscating numbers are numbered randomly to deter edits. You must use FBI to decrypt the files and their names.

**Comment by astronautlevel2** [comment] 2018-05-08 18:10
Unlikely. 00000001 is always the VSXE metadata. I'm looking at the data now, it doesn't make sense that other theme managers don't result in changes to 00000001 DIFF - for example:

00000001 original: https://cdn.discordapp.com/attachments/366999300594728960/443473918016225290/unknown.png

00000001 Anemone: https://cdn.discordapp.com/attachments/366999300594728960/443473861971804161/unknown.png

Of course adding files to a folder should change the VSXE metadata. I'm having someone dump the VSXE metadata after using Themely so hopefully I should have more information soon.

**Comment by astronautlevel2** [comment] 2018-05-08 18:11
@TurdPooCharger Nevermind, I found someone else to dump it, don't worry.

**Comment by TurdPooCharger** [comment] 2018-05-08 18:13
@astronautlevel2, make sure whoever do using Themely to delete the **000002cd** folder with no prior interaction with Anemone. It has to be a fresh one.

**Comment by CecilFF4** [comment] 2018-05-08 18:30
FYI, bodycache_rd was shown to be problematic in my tests, which I posted about 14 days ago. I didn't post about the metadata file (00000001) then because the file doesn't show up in FBI, but I do show it as being different from a working example as well.

**Comment by astronautlevel2** [comment] 2018-05-08 18:35
The bodycache only handles the actual body_lz.bin and contains no information on the BGM, so it shouldn't be causing an issue with the BGM. If the actual theme looks the same, it's not a problem with the bodycache.

**Comment by astronautlevel2** [comment] 2018-05-08 18:41
@TurdPooCharger The 00000001 DIFF container definitely differs after Themely is installed. The data is identical to Anemone's with the exception of the file Unique Identifier. I'm confident in ruling this out as the source of problems.

In addition, the fact that the DIFF container changed when compared after being extracted between Themely and the original but your testing claims they were the same throws some amount of doubt onto the validity of your testing results. You'd get much more accurate data by using GodMode9 to extract the actual DIFF container from the extdata rather than attempting to compare data that's still encrypted.

**Comment by TurdPooCharger** [comment] 2018-05-08 18:51
@astronautlevel2, every time I did the test for each theme manager, I replaced the **000002cd** folder with the originally produced clean version. I did mention I noticed there were slight changes within the files whenever that folder was rebuilt.

I don't know what more to say as that Duplicate Cleaner Pro program states **00000001** stays the same for every case except Anemone when it does theme shuffle.

**Comment by astronautlevel2** [comment] 2018-05-08 19:12
@TurdPooCharger Rather than comparing compressed and encrypted data you should use either FBI or GM9 to extract and decrypt it first. It would also tell you what data is actually being stored in each file. Unless you do this I'm going to have to doubt any of the results you've presented as being accurate, as the conclusions you drew from your data do not make any sense. In addition, your data provides other possible interesting conclusions, such as all the different files _besides_ 00000001. I'd be much more interested in extracting that data and comparing it than comparing the VSXE metadata.

**Comment by TurdPooCharger** [comment] 2018-05-08 19:35
@astronautlevel2, I don't know enough about extracting and decrypting those 16 files in GodMode9 and FBI as I don't see the options of DIFF extraction in GM9, and FBI only gives me the options of **Delete, Rename, Copy,** and **Paste** when selecting those files. At this point, I'm not entirely sure we're talking about the same thing. 

Unless my N3DSXL had a freak incident messing around with something prior to these tests that somehow fixed the BGM loop for CHMM2 and Themely but not for Anemone3DS, all that I'm technically capable of supplying you was those hash comparison data for their respective outputs.

If you guys followed my testing procedures exactly as outlined in the report and that **00000001** changed for Themely and CHMM2 too, then all I can comment from this is that my N3DSXL is the odd one out.

I have a secondary N2DS that is in my niece's possession. When she comes over next time, I'll check again if shuffle BGM loops work for here system under the those other two managers. It might be a while when she swings by.

Again, I mentioned I would like to be peered review but also did state not to cut corners in those steps as I've noticed some people tend to do this.

**Comment by TurdPooCharger** [comment] 2018-05-08 20:32
@CecilFF4, thank you. I was looking in 0:/ directory in GM9. This is new info to me. :D 
 
@astronautlevel2, do you want me to provide every single file dumped in extract DIFF for alll **000002cd** folders from the three managers done in TEST No.2 and No.3? Do you want everything?

**Comment by astronautlevel2** [comment] 2018-05-08 20:40
Fixed in #155.

**Closed by astronautlevel2** 2018-05-08 20:40 UTC
Labels: bug

**Comment by CecilFF4** [comment] 2018-05-08 20:42
@astronautlevel2 You're awesome! Thanks!

**Comment by TurdPooCharger** [comment] 2018-05-08 20:43
@astronautlevel2 , please freakin' tell me you got a nightly build for public testing.

**Comment by astronautlevel2** [comment] 2018-05-08 20:45
This was @LiquidFenrir who figured it out, not me (though I'm pretty sure I tried something similar a while ago...)

![Test build](https://cdn.discordapp.com/attachments/366999300594728960/443507788761661441/Anemone3DS.cia_qr.png)

May slow down theme install slightly but w/e

**Comment by CecilFF4** [comment] 2018-05-08 20:52
Verified working on my tests so far.

**Comment by TurdPooCharger** [comment] 2018-05-08 21:15
Can confirm that v2.0.0a-9cc7050 is working with looping BGM for shuffle.

However, that install time penalty is severe for a full set of 10 themes.
 
**Anemone3DS_v2.0.0a-95d8808a**
20 sec

**Anemone3DS_v2.0.0a-9cc7050**
2 min 25 sec

I will still look into those files for DIFF extraction as I believe the fix employed by @LiquidFenrir should be treated as a temporary solution. Nonetheless, congrats Anemone3DS team.

**Comment by astronautlevel2** [comment] 2018-05-08 21:18
That doesn't seem remotely reasonable for what the code change actually was.

**Comment by TurdPooCharger** [comment] 2018-05-08 21:38
Okay. I don't want to hold you guys to it. An increase factor of 7 in installation time is going to make a lot of 3DS users really upset. One thing at a time. We'll wait and see if you guys can improve the performance, so of course this brand spanking new fix needs time for optimization.

Still, I feel this solution didn't fix the root cause of the BGM loop bug, and it was more of brute force fix. What did Anemone do differently compared to Themely and CHMM2 that caused the change in **00000001** that I was seeing? Was that somehow related to fixing the loop bug if the 00 padding method was not employed? This is a mystery that may now not be explored more in depth as you guys came up with a solution that works but doesn't seem that ideal, IMO.

 If you guys are happy enough with this approach and want nothing more to do with loop bug and **00000001**, I'll lay off. Just give me the word.

**Comment by astronautlevel2** [comment] 2018-05-08 21:41
Again, the only difference was in whether the data was padded or not. There were no differences in 00000001 when extracted except for UUID info which is going to be different 100% of the time.

We're investigating why the padding is adding so much install time. This is almost certainly a bug and not a reasonable increase in time given the changes. I'm going to lock this conversation for now. We know what the fix is and know we need to optimize it so there's no reason for this issue to stay open in the meantime. I'll comment again once we figure out what's causing the delay.

**Comment by astronautlevel2** [comment] 2018-05-08 22:18
Fixed in latest master commit. 

https://cdn.discordapp.com/attachments/366999300594728960/443534550627516416/Anemone3DS-padded-buffers-attempt.cia_qr.png
