### ISSUE TITLE
Anemone3DS hangs when dspfirm.cdc is not present

### ISSUE THREAD

**Issue by EricKY26** [astronautlevel2/Anemone3DS#173] opened 2018-05-28 02:51 UTC
how to quit theme preview? 
i tried every button and it just freeze in the preview mode

**Comment by Helloman892** [comment] 2018-05-28 19:14
Did you try pressing `Y` again?

**Comment by EricKY26** [comment] 2018-05-29 04:55
@Helloman892  I tried pressing Y again, nothing happened

**Comment by EricKY26** [comment] 2018-05-29 05:03
@astronautlevel2  The theme is called "Dragon Ball Super", it's in Themeplaza, the url is https://themeplaza.eu/item/6722
I can't quit preview mode in the browser of anemone3ds, i tried download the theme through anemone3ds and enter preview mode  from anemone3ds locally, I just can't quit preview mode, i tried pressing Y again, nothing happened. I could only reboot to quit

**Comment by astronautlevel2** [comment] 2018-05-29 18:50
Cannot reproduce, works fine on my console.

Are you sure you're using v2.0.1 and not v2.0.0?

**Comment by EricKY26** [comment] 2018-05-30 02:04
@astronautlevel2 not only this theme,  I tried other themes, also get stuck in the preview mode. 

And I'm sure that I'm using v2.0.1. But the BGM preview does not play at all. I was confused about that too. And now that you mentioned, I think maybe that's the reason.
![anemone3ds version](https://user-images.githubusercontent.com/19644162/40694827-dcb76f40-63f0-11e8-8856-ba23b58b796b.jpg)

**Comment by astronautlevel2** [comment] 2018-05-30 02:07
Unfortunately without being able to replicate it, there's not much I can do to try to debug it.

I have a few ideas as to what may be causing it, primarily failed initialization of something in NDSP... somehow. I'll send you a few debug builds tomorrow so we can try to nail out the issue, but right now it's getting late here and I won't have time tonight.

Thanks for your patience!

**Comment by EricKY26** [comment] 2018-05-30 02:18
Thank you very much. I appericiate your work. I'm not in a hurry. so take your time please.

**Comment by AlphaLiu** [comment] 2018-05-31 09:08
Hi , I also met this issue. Has to shutdown the power. My console is 2DSLL.

**Comment by TurdPooCharger** [comment] 2018-05-31 18:49
@EricKY26 and @AlphaLiu , do either of you have **dspfirm.cdc** in the 3ds folder?

**Comment by astronautlevel2** [comment] 2018-06-01 00:10
I was able to replicate this on the .3dsx version after deleting the dspfirm.cdc, which means I'm not catching something with NDSP failing initialization properly.

**Comment by AlphaLiu** [comment] 2018-06-01 01:08
After installed the DSP1, the issue gone. Thank you.

**Comment by EricKY26** [comment] 2018-06-01 03:19
I installed the cia version of Anemone3DS, not the 3dsx version. but still have the preview problem.
I don't have dspfirm.cdc in my 3ds folder. So I installed the DSP firm dumper in the link above. And after I run the DSP firm dumper, the preview issue gone. Great work! Thank you guys!

And btw, is the DSP firm dumper essential for the Anemone3ds working? I don't know that, is there a guide for noob?

**Comment by TurdPooCharger** [comment] 2018-06-01 03:44
@EricKY26, DSP firm is needed for basically all homebrew titles that require the use of sound. 

_Section V - DSP Dump_
https://3ds.hacks.guide/finalizing-setup

Yah, it's one of those prep works you do installing CFW that you need but almost no one tells you why. Easy to miss. Glad to hear it's fixed.

**Comment by astronautlevel2** [comment] 2018-06-01 11:57
Huh, I was under the impression that the CIA version shouldn't need a dumped dspfirm.cdc, interesting.

**Comment by EricKY26** [comment] 2018-06-04 14:53
@TurdPooCharger Thank you!

**Comment by astronautlevel2** [comment] 2018-06-06 20:27
Fixed in https://github.com/astronautlevel2/Anemone3DS/commit/9847d47bf7fcf9cbd39cda97977af61d0ee5424c

**Closed** 2018-06-06 20:29 UTC
Labels: bug, could not reproduce
